### ISSUE TITLE
在钉钉微应用里window.location.reload(),buijs会报错

### ISSUE THREAD

**Issue by doscanner** [imouou/BUI-Guide#77]
在钉钉微应用里，使用window.location.reload()重新加载页面，会报如下错误：
Uncaught TypeError: Cannot read property 'find' of null  at：2019-05-31 14:24:03 bui.js:8:4283
at o (http://localhost:6655/content/js/bui.js:8:4283)
at http://localhost:6655/content/js/bui.js:8:8317
at success (http://localhost:6655/content/js/bui.js:8:10164)
at ajaxSuccess (http://localhost:6655/content/js/zepto.js:1309:26)
at XMLHttpRequest.xhr.onreadystatechange (http://localhost:6655/content/js/zepto.js:1490:26)

设备 Samsung/Samsung SM-G9550
操作系统 Android 9
分辨率 412*846
客户端 Alibaba DingTalk 4.5

**Comment by imouou** [comment]
bui什么版本，什么控件？使用官方例子会不会？

**Comment by doscanner** [comment]
BUI v1.5.2

**Comment by imouou** [comment]
跑下官方示例包还原你的场景看会不会

**Comment by doscanner** [comment]
一样的

**Comment by doscanner** [comment]
不知道什么原因，更新钉钉App为最新版，这个问题就没了
