### ISSUE TITLE
如何在页面每次展示的时候执行？

### ISSUE THREAD

**Issue by shoppingzh** [imouou/BUI-Guide#81]
请问，A页面跳转到B页面，B页面再返回A页面时，如何在A页面展示后执行逻辑？
B页面在back时可以在callback回调里调用A模块抛出的方法，这个方法虽然可行，但是A页面在此处是一个首页，它可以跳转到很多的页面，大多数情况在页面返回A页面时都需要对A页面进行局部刷新，不想每个页面都在返回回调里调用A页面的刷新方法，想通过A页面的页面展示事件回调后调用自身的刷新方法，可以这样做吗？如果可以，怎么做是最佳实践？求指导。

**Comment by imouou** [comment]
新版有当前模块的生命周期, 在show 的时候, 前进后退都会触发, 可以在这里实现局部刷新.
如果是旧版, 可以在首页使用 router.on("back",function(){}) 全局监听也能实现, 只是维护是在首页, 不是在对应的模块里.

**Comment by shoppingzh** [comment]
嗯，是的，我有在文档模块化-单页生命周期中看到该内容，看到了这种使用方法：
```
loader.define({
  show: function(){  }
});
```
但是我使用这种方法定义时显示参数错误，这里的单页回调事件应该如何定义，在哪里定义，请指导一下，谢谢！

**Comment by imouou** [comment]
loaded 是必须有的, 
效果查看chrome log面板: http://www.easybui.com/demo/#pages/router/life/life
可以参考这个源码 : 
http://www.easybui.com/demo/source.html?url=pages/ui_loader/life&code=html,js,result

**Comment by shoppingzh** [comment]
刚刚我试了一下发现beforeCreate/created/beforeLoad/loaded/beforeDestroy/destroyed回调都能触发，但show/hide回调无法触发，并且官网demo中的也是这样，请问这是什么原因导致的？
我以为是版本问题，于是我升级了bui的版本（1.5.2 -> 1.5.3），发现问题非但没有解决，还报了下面的错误：
```
Uncaught DOMException: Failed to execute 'pushState' on 'History': function(e,t){var n=this;for(var i in n){var a=n[i];try{if((a&&a[t]||a)==e)return parseInt(i)}catch(e){}}return-1} could not be cloned.
    at Object.le.add (http://192.168.1.110:8080/suite/app/js/bui.js?v=20190611:8:18755)
    at Object.d [as load] (http://192.168.1.110:8080/suite/app/js/bui.js?v=20190611:8:11335)
    at Object.<anonymous> (http://192.168.1.110:8080/suite/app/pages/course/teacher/teachingPlan.js:125:32)
    at Object.<anonymous> (http://192.168.1.110:8080/suite/app/js/zepto.js:1983:57)
    at fire (http://192.168.1.110:8080/suite/app/js/zepto.js:1854:43)
    at Object.fireWith [as resolveWith] (http://192.168.1.110:8080/suite/app/js/zepto.js:1929:30)
    at Object.deferred.<computed> [as resolve] (http://192.168.1.110:8080/suite/app/js/zepto.js:2019:44)
    at t (http://192.168.1.110:8080/suite/app/js/bui.js?v=20190611:13:6055)
    at ajaxSuccess (http://192.168.1.110:8080/suite/app/js/zepto.js:1309:26)
    at XMLHttpRequest.xhr.onreadystatechange (http://192.168.1.110:8080/suite/app/js/zepto.js:1490:26)
```

**Comment by imouou** [comment]
是版本问题, 只有1.5.3 以后才会有 show , 另外刚刚官网的demo 的脚本没有更新, 刷新可以看到 http://www.easybui.com/demo/#pages/router/life/life  , 源码里的show不会运行, 因为那是走的多页开发, 没有show

**Comment by shoppingzh** [comment]
谢谢！我的问题已经解决。
